sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="hijub"
  - DOCKER_HUB_ORG="purnamasftr"
before_install:
- openssl aes-256-cbc -K $encrypted_2a9a5107d0e2_key -iv $encrypted_2a9a5107d0e2_iv -in restfulapi/deploy_rsa.enc -out restfulapi/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 restfulapi/deploy_rsa
- ssh-add restfulapi/deploy_rsa
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x restfulapi/deploy.sh
- sudo chmod 600 restfulapi/deploy_rsa
after_script:
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:deployment2
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:deployment2
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i restfulapi/deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh
#test
